[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "syncy"
version = "0.0"
description = "Sync Workspaces!"
authors = [
    {name = "Tyler Hughes", email = "tylerxh111+git@proton.me"},
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
keywords = [
    "sync",
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Typing :: Typed",
]
dependencies = []

[project.optional-dependencies]
toml = [
    "toml",
]
dotenv = [
    "dotenv",
]

[project.scripts]
syncy = "syncy:entrypoint"

[project.urls]
source        = "https://github.com/tylerh111/syncy"
issues        = "https://github.com/tylerh111/syncy/issues"
changes       = "https://github.com/tylerh111/syncy/blob/main/CHANGES.md"

[tool.bumpver]
current_version = "0.0"
version_pattern = "MAJOR.MINOR[.PATCH][-TAG]"
commit_message = "release version {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"LICENSE.md" = [
    'Copyright (c) 2025-YYYY',
]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"syncy.py" = [
    '__date__ = "YYYY-0M-0D"',
    '__copyright__ = "Copyright (c) 2025-YYYY Tyler Hughes"',
    '__version__ = "{version}"',
]

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
# see rules at https://docs.astral.sh/ruff/rules
extend-select = ["RUF", "C90", "UP", "I", "D"]
extend-ignore = ["D105", "D107", "F541", ]
unfixable = ["B"]
mccabe = { max-complexity = 14 }
pydocstyle = { convention = "google" }

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff.format]
quote-style = "double"
